'use client';
import { useState } from 'react';
import NTAssist from './NTAssist';
import QuoteForm from './QuoteForm';

const products = [
  ['Industrial Hardware', 'Components', 'Dependable hardware and components for production, maintenance and assembly requirements.', 'Manufacturing / Machinery / Maintenance'],
  ['Packaging Material', 'Materials', 'Practical materials for protecting finished goods, handling products safely and keeping dispatch moving.', 'Packing / Dispatch / Protection'],
  ['Flexographic Printing Machines', 'Printing systems', 'Flexographic printing solutions for packaging and converting operations, matched to the application.', 'Flexible Packaging / Converting'],
  ['Doctor Blades', 'Printing consumables', 'Doctor blade solutions for controlled ink metering and clean, consistent print transfer.', 'Flexographic Printing / Ink Control'],
  ['Side Packing Foam', 'Protection', 'Protective foam solutions that help cushion, space and secure products through storage and transport.', 'Carton Packing / Product Protection'],
  ['Diaphragms', 'Industrial components', 'Application-focused diaphragm solutions for systems that require dependable flexible sealing components.', 'Pumps / Valves / Process Equipment'],
  ['Ceramic Rollers', 'Printing components', 'Ceramic roller solutions for printing and converting processes where surface performance matters.', 'Printing / Coating / Lamination'],
  ['Woven Sack Technical Consultancy', 'Technical support', 'Practical production guidance for woven sack manufacturers, tailored to process challenges.', 'Woven Sack Manufacturing / Troubleshooting']
];

const industries = [
  ['Flexible Packaging', 'Material and flexographic printing solutions for packaging operations.', 'Packaging Material · Doctor Blades'],
  ['Plastic & Polymer Manufacturing', 'Industrial materials and components for production-focused requirements.', 'Industrial Hardware · Diaphragms'],
  ['Printing Industry', 'Solutions supporting flexographic printing applications and converting work.', 'Printing Machines · Ceramic Rollers'],
  ['Woven Sack Manufacturing', 'Technical support for woven sack applications and process requirements.', 'Technical Consultancy'],
  ['Industrial Manufacturing', 'Materials and components for specific industrial needs.', 'Hardware · Diaphragms'],
  ['Packaging Industry', 'Practical materials for packaging, handling and product protection.', 'Packaging Material · Side Packing Foam']
];

const matrix = [
  ['Flexible Packaging', 'Printing and packaging production', 'Printing Machines · Doctor Blades · Ceramic Rollers'],
  ['Plastic & Polymer Manufacturing', 'Production and process equipment', 'Industrial Hardware · Diaphragms'],
  ['Printing Industry', 'Flexographic printing and converting', 'Printing Machines · Doctor Blades · Ceramic Rollers'],
  ['Woven Sack Manufacturing', 'Process requirements and troubleshooting', 'Technical Consultancy'],
  ['Packaging Industry', 'Packing and product protection', 'Packaging Material · Side Packing Foam']
];

const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });

export default function Site() {
  const [assist, setAssist] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const event = (name) => typeof window !== 'undefined' && window.dispatchEvent(new CustomEvent('nt-event', { detail: name }));
  const ask = (text) => { setPrompt(text); setAssist(true); };
  const go = (id) => { setMenuOpen(false); scrollTo(id); };

  return <>
    <header className="site-header"><div className="nav wrap"><a href="#top" className="brand" onClick={() => setMenuOpen(false)}>NT<span>.</span> ENTERPRISES<small>INDUSTRIAL SOLUTIONS</small></a><button className="menu-toggle" type="button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span></span><span></span><span></span></button><nav className={menuOpen ? 'nav-links open' : 'nav-links'} aria-label="Primary navigation">{['catalogue:Catalogue', 'solutions:Solutions', 'industries:Industries', 'about:About', 'contact:Contact'].map(item => { const [id, label] = item.split(':'); return <a key={id} href={'#' + id} onClick={() => setMenuOpen(false)}>{label}</a>; })}</nav><button className="button button-dark nav-quote" onClick={() => { event('quote_started'); go('quote'); }}>Request a Quote <b>↗</b></button></div></header>
    <main id="top">
      <section className="hero"><div className="blueprint" aria-hidden="true"><div className="ring ring-one"></div><div className="ring ring-two"></div><div className="axis axis-x"></div><div className="axis axis-y"></div><span className="measure measure-top">DIAMETER 220 / NT-01</span><span className="measure measure-side">PRECISION / 01</span></div><div className="wrap hero-inner"><p className="eyebrow">NT ENTERPRISES / INDUSTRIAL SOLUTIONS</p><h1>Industrial Solutions<br /><em>Built Around Reliability.</em></h1><p className="hero-copy">NT Enterprises supplies industrial materials, printing solutions and technical expertise for businesses that demand dependable performance.</p><div className="hero-actions"><a className="button button-brass" href="#catalogue">Explore Solutions <b>→</b></a><a className="button button-light" href="#quote">Request a Quote <b>→</b></a><button className="text-button" onClick={() => ask('I need help identifying an NT Enterprises solution for my application.')}>Talk to NT Assist <b>↗</b></button></div><div className="hero-foot"><span>INDUSTRIAL MATERIALS / TECHNICAL SOLUTIONS / B2B SUPPLY</span><span>NASHIK / MAHARASHTRA / INDIA</span></div></div></section>
      <section id="catalogue" className="section catalogue"><div className="wrap"><div className="section-head"><div><p className="eyebrow">01 / INDUSTRIAL SOLUTIONS</p><h2>Products that keep production moving.</h2></div><p>Materials, machinery, components and technical support selected around the work your operation needs to do.</p></div><div className="product-grid">{products.map(([name, category, desc, use], i) => <article className="product-card" key={name}><div className={'product-visual product-visual-' + ((i % 4) + 1)} aria-hidden="true"><span></span><i></i><b></b></div><div className="product-top"><span className="product-number">{String(i + 1).padStart(2, '0')}</span><span className="product-category">{category}</span></div><div className="product-mark">{String(i + 1).padStart(2, '0')}</div><h3>{name}</h3><p>{desc}</p><div className="product-use"><span>APPLICATIONS</span>{use}</div><button onClick={() => ask(`Tell me about ${name} and where it is commonly used according to NT Enterprises' product information.`)}>View solution <b>→</b></button></article>)}</div></div></section>
      <section id="solutions" className="solution-band"><div className="wrap solution-layout"><div><p className="eyebrow">CONNECTED SUPPORT</p><h2>From machine to<br /><em>finished package.</em></h2></div><div><p>NT Enterprises brings together printing solutions, packaging materials, industrial components and application-focused guidance for the production chain.</p><a href="#quote" className="text-button">Tell us what you are making <b>→</b></a></div></div></section>
      <section id="industries" className="section industries"><div className="wrap"><div className="section-head"><div><p className="eyebrow">02 / APPLICATION FOCUS</p><h2>Industries we serve.</h2></div><p>Industrial solutions across applications where reliability and technical understanding matter.</p></div><div className="industry-grid">{industries.map(([name, desc, tags], i) => <article key={name}><span className="industry-number">{String(i + 1).padStart(2, '0')}</span><h3>{name}</h3><p>{desc}</p><small>{tags}</small><button onClick={() => ask(`I work in ${name}. What NT Enterprises solutions may be relevant to my application?`)}>Explore industry <b>→</b></button></article>)}</div></div></section>
      <section className="section why"><div className="wrap"><div className="section-head"><div><p className="eyebrow">03 / THE NT APPROACH</p><h2>Why businesses choose NT.</h2></div><p>We understand the application before recommending a solution, and stay involved through supply and support.</p></div><div className="why-grid">{[['Quality', 'Reliable industrial products selected for demanding applications.'], ['Reliability', 'Consistent supply and dependable product performance.'], ['Technical Expertise', 'Practical understanding to help identify the right solution.'], ['Responsive Support', 'Clear communication from requirement to delivery.']].map(([title, desc], i) => <article key={title}><span className="product-number">{String(i + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section className="section matrix"><div className="wrap"><div className="section-head"><div><p className="eyebrow">04 / WHERE WE WORK</p><h2>Match your process to a solution.</h2></div></div><div className="table-wrap"><table><thead><tr><th>Industry</th><th>Application</th><th>Relevant solutions</th></tr></thead><tbody>{matrix.map(row => <tr key={row[0]}>{row.map((cell, i) => <td key={cell} className={i === 0 ? 'table-industry' : ''}>{cell}</td>)}</tr>)}</tbody></table></div><a href="#quote" className="button button-dark matrix-cta">Discuss your requirement <b>→</b></a></div></section>
      <section className="assist-banner"><div className="wrap assist-layout"><div><p className="eyebrow">05 / NT ASSIST</p><h2>Have a requirement?<br /><em>Talk to NT Assist.</em></h2><p className="assist-intro">Describe your application, material or machine requirement. NT Assist uses approved NT Enterprises information to help guide the next step.</p><div className="assist-points"><span>Application-led guidance</span><span>Verified product information</span><span>Quote-ready requirements</span></div><button className="button button-brass" onClick={() => ask('I need help with an industrial requirement.')}>Open NT Assist <b>↗</b></button></div><div className="assist-preview"><div><span className="status"></span> NT ASSIST <small>INDUSTRIAL SOLUTIONS ASSISTANT</small></div><p>Start with your product, process or requirement. The assistant will help you find the relevant NT solution.</p><button onClick={() => ask('Tell me what you are manufacturing or what application you are working with, and I will help identify the relevant NT Enterprises solution.')}>Start a conversation <b>→</b></button></div></div></section>
      <section className="section process"><div className="wrap"><p className="eyebrow">06 / WORKING WITH US</p><h2>How we help.</h2><div className="steps">{[['Understand', 'We understand the application, specification and requirement.'], ['Recommend', 'We identify suitable products or technical solutions.'], ['Supply', 'We coordinate reliable supply and delivery.'], ['Support', 'We remain available for technical and product support.']].map(([title, desc], i) => <article key={title}><span>{String(i + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
      <section id="quote" className="section quote"><div className="wrap quote-layout"><div><p className="eyebrow">07 / REQUEST A QUOTE</p><h2>Tell us what<br /><em>you need.</em></h2><p className="quote-copy">Share your product, application and technical requirement. Our team will respond with the right next step.</p><div className="quote-notes"><span>TECHNICAL REQUIREMENTS</span><span>PRODUCT ENQUIRIES</span><span>BULK REQUIREMENTS</span><span>INDUSTRIAL SOLUTIONS</span></div><button className="text-button" onClick={() => ask('Help me structure my requirement for an NT Enterprises quotation.')}>Need help describing it? <b>Ask NT Assist ↗</b></button></div><QuoteForm onAssist={() => ask('Help me structure my requirement for an NT Enterprises quotation.')} /></div></section>
      <section id="about" className="about"><div className="wrap about-layout"><div><p className="eyebrow">08 / ABOUT NT ENTERPRISES</p><h2>Where quality meets reliability, and innovation meets tradition.</h2></div><div><p>NT Enterprises supplies industrial materials, printing solutions and technical consultancy to manufacturers who depend on consistent quality. Our range spans industrial hardware, packaging material, flexographic printing machines, doctor blades, side packing foam, diaphragms, ceramic rollers and woven sack technical consultancy.</p><p>We work closely with each customer to understand their specific requirement before recommending a product, and stay involved through supply and application support, not just the point of sale.</p></div></div></section>
      <section className="final-cta"><div className="wrap"><p className="eyebrow">READY TO START?</p><h2>Let's build the right solution.</h2><p>Have a product requirement, technical question or bulk enquiry? Talk to NT Enterprises.</p><div><a href="#quote" className="button button-dark">Request a Quote <b>→</b></a><a href="#contact" className="button button-outline">Contact NT <b>↗</b></a></div></div></section>
    </main>
    <footer id="contact"><div className="wrap footer-grid"><div className="footer-brand"><div className="brand">NT<span>.</span> ENTERPRISES<small>INDUSTRIAL SOLUTIONS</small></div><p>Industrial materials, printing solutions and technical expertise for dependable production.</p></div><div><h4>Solutions</h4>{products.map(([name]) => <a key={name} href="#catalogue">{name}</a>)}</div><div><h4>Industries</h4>{industries.map(([name]) => <a key={name} href="#industries">{name}</a>)}</div><div><h4>Contact</h4><a href="tel:+919998007280" onClick={() => event('contact_clicked')}>+91 9998007280</a><a href="mailto:enterprisesnt2022@gmail.com" onClick={() => event('contact_clicked')}>enterprisesnt2022@gmail.com</a><a target="_blank" rel="noreferrer" onClick={() => event('whatsapp_clicked')} href="https://wa.me/919998007280?text=Hello%20NT%20Enterprises%2C%20I%20would%20like%20to%20enquire%20about%20an%20industrial%20requirement.">WhatsApp ↗</a></div><small className="footer-bottom">GSTIN: 27DSTPS4361C1ZA <span>© 2026 NT Enterprises. All rights reserved.</span></small></div></footer>
    <button className="assist-fab" type="button" aria-label="Open NT Assist chatbot" onClick={() => ask('I need help with an industrial requirement.')}><span className="assist-fab-dot"></span><span>NT Assist</span><b>↗</b></button>
    <NTAssist open={assist} initialPrompt={prompt} onClose={() => setAssist(false)} />
  </>;
}
